# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_a', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Value A')),
                ('value_b', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Value B')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='sites.Site')),
            ],
            options={
                'verbose_name': 'Summary',
                'verbose_name_plural': 'Summaries',
            },
        ),
    ]
